version: "3.8"
services:
  sentiment_analyzer_api_gatway:
    platform: linux/x86_64
    build: ./app
    image: app
    env_file:
      - ./.env
    ports:
      - "8082:8082"
    command: [ "python3.9", "__main__.py" ]