openapi: 3.0.0

servers:
  - url: https://172.17.0.1/internal/sentiment_analysis

info:
  version: 1.0.0
  title: Sentiment Analyzer Service API Gateway
  contact:
    email: sanyam12sks@gmail.com

paths:
  /health:
    get:
      summary: check server status
      description: check server status
      tags:
        - CRUD API
      operationId: endpoints.core.health
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string

  /analyse/text:
    post:
      summary: Send text for Sentiment Analysis
      description: Check the sentiment of the text
      tags:
        - URL
      operationId: endpoints.core.analyse_text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/analyse_text'
      responses:
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object


components:
  schemas:
    analyse_text:
      type: object
      required:
        - text
      properties:     
        url:
          type: string
    